garmin:
  log:
    result: false
    url: false

  url-base:
    get-activities: https://connect.garmin.com
    follow-ticket: https://connect.garmin.com
    login: https://sso.garmin.com
    lt-lookup: https://sso.garmin.com
